"""Init

Revision ID: 7454da140c9b
Revises: 
Create Date: 2025-10-22 13:26:24.369502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7454da140c9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Имя'),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.String(length=100), nullable=False, comment='id фотографии в телегам'),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('file_size', sa.BIGINT(), nullable=False),
    sa.Column('sort_order', sa.SMALLINT(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('name', sa.Text(), nullable=False, comment='Сообщение из поста'),
    sa.Column('hash', sa.Text(), nullable=False, comment='Хэш сессии'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=30), nullable=False, comment='Имя'),
    sa.Column('emoji', sa.Unicode(length=14), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Логин пользователя'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='Пароль'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия'),
    sa.Column('contact', sa.Boolean(), nullable=True, comment='В вашем списке контактов'),
    sa.Column('mutual_contact', sa.Boolean(), nullable=True, comment='В списке контактов ваших друзей'),
    sa.Column('phone', sa.String(length=25), nullable=True, comment='Номер телефона'),
    sa.Column('language_code', sa.String(length=10), nullable=True, comment='Язык'),
    sa.Column('access_hash', sa.BIGINT(), nullable=True, comment='Hash для отправки сообщений'),
    sa.Column('is_premium', sa.Boolean(), nullable=True, comment='Премиум подписка'),
    sa.Column('ads_publacated', sa.SMALLINT(), nullable=True, comment='Количество рекламных сообщений отправленных пользователем'),
    sa.Column('is_banned', sa.Boolean(), nullable=True, comment='Пользователь забанен'),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'USER', 'GUEST', 'BOT', name='userrole'), server_default='USER', nullable=False, comment='Роль пользователя'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Электронная почта'),
    sa.Column('info', sa.String(length=100), nullable=True, comment='Доп информация'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Является подписчиком канала'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cat_ads',
    sa.Column('bot_message_title', sa.String(length=200), nullable=True, comment='Сообщения от бота'),
    sa.Column('status', sa.Enum('NEW_BORN', 'AWAIT_MODERATING', 'APPROVED', 'REJECTED', 'PUBLICATED', name='adstatus'), server_default='NEW_BORN', nullable=False, comment='Статус объявления'),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Имя'),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='catgenders'), nullable=False, comment='Пол'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Цена'),
    sa.Column('contacts', sa.String(length=200), nullable=False, comment='Контактные данные'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='Дата рождения'),
    sa.Column('color', sa.String(length=200), nullable=False, comment='Цвет'),
    sa.Column('cattery', sa.String(length=200), nullable=True, comment='Питомник'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_ads_author_id'), 'cat_ads', ['author_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False, comment='id поста из telegram'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False, comment='Дата создания поста.'),
    sa.Column('edit_date', sa.DateTime(timezone=True), nullable=True, comment='Дата Изменения поста.'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='Название поста.'),
    sa.Column('message', sa.Text(), nullable=False, comment='Сообщение из поста'),
    sa.Column('author_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Категория поста'),
    sa.Column('views', sa.Integer(), nullable=True, comment='Количество просмотров'),
    sa.Column('forwards', sa.Integer(), nullable=True, comment='Количество пересылок'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_invites',
    sa.Column('user_invited', sa.Integer(), nullable=False, comment='Приглашённый пользователь'),
    sa.Column('user_inviting', sa.Integer(), nullable=False, comment='Кто пригласил'),
    sa.CheckConstraint('user_invited != user_inviting', name='check_different_users'),
    sa.ForeignKeyConstraint(['user_invited'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_inviting'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_invited', 'user_inviting'),
    sa.UniqueConstraint('user_invited', 'user_inviting')
    )
    op.create_table('cat_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cat_ad_id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cat_ad_id'], ['cat_ads.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id', 'cat_ad_id', 'photo_id')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    op.drop_table('cat_photos')
    op.drop_table('user_invites')
    op.drop_table('posts')
    op.drop_index(op.f('ix_cat_ads_author_id'), table_name='cat_ads')
    op.drop_table('cat_ads')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_table('sessions')
    op.drop_table('photos')
    op.drop_table('categories')
    # ### end Alembic commands ###
