version: '3.8'

services:
  bot:
    build: .
    container_name: mainecoon_bot
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: bash -c "python main.py"
    volumes:
      - ./logs/:/app/logs/
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13-alpine
    container_name: mainecoon_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  redis:
    image: redis:7-alpine
    container_name: mainecoon_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: